#1 initialize project structure
Web-tree/spring-social-stackexchange pull request #3
Opened 2018-10-07 10:56 UTC by UdjinSkobelev

2018-10-10 05:06 UTC, Max-Levitskiy commented on pom.xml
> +            <artifactId>spring-social-facebook</artifactId>
Why do you have facebook here? :)

2018-10-10 05:06 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/StackExchange.java
> +public interface StackExchange extends Api{
You shouldn't have here methods from Api. Use composition vs inheritance.

2018-10-10 05:06 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +            switch (code) {
Transform to map

2018-10-10 05:06 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +        } catch (JsonParseException var13) {
don't use var13 name. it's awful. :)

2018-10-10 05:07 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +            return null;
why do you return null?

2018-10-10 05:08 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +    private String apiVersion = "2.2";
extract in properties file

2018-10-10 15:36 UTC, Max-Levitskiy requested changes

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +    private String readResponseJson(ClientHttpResponse response) throws IOException {
Why do you do this? As I remember, Jackson can read from input stream for you.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        return "https://api.stackexchange.com/" + apiVersion + "/";
Don't build this string each time. You can create it in constructor and use as a field in class.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        return getRestTemplate().exchange(uri, HttpMethod.GET, null, new ParameterizedTypeReference<ResponseWrapper<T>>() {
Why do you call getter for restTemplate?

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +    private FormHttpMessageConverter getFormMessageConverter() {
get -> create

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +    private MappingJackson2HttpMessageConverter getJsonMessageConverter() {
get -> create

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        List<HttpMessageConverter<?>> partConverters = new ArrayList();
extract partConverter as method

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        List messageConverters = getMessageConverters();
You've lost generic here. :)

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        RestTemplate client = new RestTemplate(messageConverters);
Don't create useless variables. Just return.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        List<HttpMessageConverter<?>> messageConverters = new ArrayList();
ArrayList<>

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +    private void initSubApis() {
What is SubApis? it's bad name. Create operations is better. Delegate creation or even just providing this operations for somebody else is much better.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        this.userOperations = new UserTemplate(this, getRestTemplate());
You definitely shouldn't create cyclic dependency here. The problem came from StackExchange extends Api

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/UserTemplate.java
> +    private final RestTemplate restTemplate;
You don't use restTemplate here. Remove it.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/converter/UnixTimestampToMillisecondsConverter.java
> +public class UnixTimestampToMillisecondsConverter extends JsonDeserializer<Date> {
This name is lying. It converts timestamp in milliseconds to date.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/domain/NetworkUser.java
> +    @JsonProperty("question_count")
Maybe you can create some default converter which will automatically map underscores to camel case. I think it's not a new problem. :)

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/domain/User.java
> +    public boolean equals(Object o) {
Replace all equals-hashcodes to other template based on java.util.Objects (in idea - last option on generation), It produce less boilerplate code.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandlerTest.java
> +public class StackExchangeErrorHandlerTest {
Seems this test should be refactored to parameterized test. Maybe it's better to migrate all tests to junit5?

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/api/impl/UserTemplateTest.java
> +        server.verify();
extract to tearDown method

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/AbstractApiIntegrationTest.java
> +        TOKEN =  System.getenv("stackexchange.token");
stackexchange.token -> stackexchange_token

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/AbstractApiIntegrationTest.java
> +        APP_KEY = System.getenv("stackexchange.key");
stackexchange.key -> stackexchange_key

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/SiteTemplateIntegrationTest.java
> +        assertThat(selectedSite.get().getName()).isNotNull();
You can check real site name here. There is a small chance they change it. :) 
Or at least not empty string.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/UserTemplateIntegrationTest.java
> +        assertThat(users.get(0).getAccountId()).isNotNull();
Again, not empty string would be better.

2018-10-10 15:36 UTC, Max-Levitskiy commented on src/test/java/org/webtree/social/stackexchange/converter/UnixTimestampToMillisecondsConverterTest.java
> +        Date dateAfterConverting = new Date(TimeUnit.SECONDS.toMillis(Long.valueOf(UNIX_TIME_IN_SECONDS)));
Don't create copy-paste between test and production code. If there is a problem in logic your test won't find it. 
Here you should use a pair of unix and date from human readable format. The first one should be returned from mock, the second one should be used in accertion.

2018-10-13 14:59 UTC, UdjinSkobelev commented on pom.xml
> +            <artifactId>spring-social-facebook</artifactId>
Mistake, deleted/

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        List messageConverters = getMessageConverters();
Now not.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        RestTemplate client = new RestTemplate(messageConverters);
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        List<HttpMessageConverter<?>> messageConverters = new ArrayList();
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/UserTemplate.java
> +    private final RestTemplate restTemplate;
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +    private FormHttpMessageConverter getFormMessageConverter() {
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +    private MappingJackson2HttpMessageConverter getJsonMessageConverter() {
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeTemplate.java
> +        this.userOperations = new UserTemplate(this, getRestTemplate());
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/converter/UnixTimestampToMillisecondsConverter.java
> +public class UnixTimestampToMillisecondsConverter extends JsonDeserializer<Date> {
Unix timestamp in seconds :)
UnixTimeStampToDate

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/domain/User.java
> +    public boolean equals(Object o) {
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/UserTemplateIntegrationTest.java
> +        assertThat(users.get(0).getAccountId()).isNotNull();
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/SiteTemplateIntegrationTest.java
> +        assertThat(selectedSite.get().getName()).isNotNull();
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/AbstractApiIntegrationTest.java
> +        TOKEN =  System.getenv("stackexchange.token");
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/api/impl/integration/AbstractApiIntegrationTest.java
> +        APP_KEY = System.getenv("stackexchange.key");
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/api/impl/UserTemplateTest.java
> +        server.verify();
Done

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/StackExchange.java
> +public interface StackExchange extends Api{
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +        } catch (JsonParseException var13) {
Renamed

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +    private String readResponseJson(ClientHttpResponse response) throws IOException {
fixed

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +            return null;
fixed

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/domain/NetworkUser.java
> +    @JsonProperty("question_count")
Done/

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandlerTest.java
> +public class StackExchangeErrorHandlerTest {
Done.

2018-10-13 14:59 UTC, UdjinSkobelev commented on src/test/java/org/webtree/social/stackexchange/converter/UnixTimestampToMillisecondsConverterTest.java
> +        Date dateAfterConverting = new Date(TimeUnit.SECONDS.toMillis(Long.valueOf(UNIX_TIME_IN_SECONDS)));
Done

2018-10-16 15:18 UTC, Max-Levitskiy requested changes

2018-10-16 15:18 UTC, Max-Levitskiy commented on pom.xml
> +            <artifactId>spring-boot-starter-test</artifactId>
Why do you need spring boot here?

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/ErrorCodes.java
>      public static final int BAD_PARAMETER = 400;
You have http codes constants here: java.net.HttpURLConnection.

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/StackExchange.java
> +    String getBaseApiUrl();
why do you have this method on high level interface? I see usage only in test and don't see a reason for have it here.

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/StackObjectFetcher.java
>      <T> ResponseWrapper<T> fetchObject(String methodName, Class<T> itemsType);
fetchObject -> fetch

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +            .put(UNKNOWN_ERROR, (error) -> {
It's wrong logic. You should make default handling in handleError() if this map does not contain error code. Now you missed situation with default case (new error code will fail with null pointer).

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +
Remove empty lines

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +            return new StackExchangeError(0, "Something goes wrong", null);
It's yours exception. Don't put nulls and magic numbers there. 
And it's not "unknown" exception. When you re-throw exception, you shouldn't lose any information.
Here you have JsonParseException. Only its name told a lot. Also it has two properties.

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackObjectFetcherImpl.java
> +                return new ParameterizedTypeImpl((ParameterizedType) super.getType(), new Type[]{type});
Why do you implement this? Oo 
For get correct type you just need to have this 
`new ParameterizedTypeReference<ResponseWrapper<T>>(){}`

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackObjectFetcherImpl.java
> +public class StackObjectFetcherImpl implements StackObjectFetcher {
Missed test

2018-10-16 15:18 UTC, Max-Levitskiy commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackObjectFetcherImpl.java
> +                return new ParameterizedTypeImpl((ParameterizedType) super.getType(), new Type[]{itemsType});
same here

2018-10-16 15:18 UTC, Max-Levitskiy commented on pom.xml
> +                        <exclude>**/integration/*.java</exclude>
Move integration tests in separate package. It shouldn't be excluded by stars. How are you gonna run just units from IDE? :)

2018-10-16 19:07 UTC, UdjinSkobelev commented on src/main/java/org/webtree/social/stackexchange/api/impl/StackExchangeErrorHandler.java
> +
Done

2018-10-31 10:07 UTC, merged